### ISSUE TITLE
Position of the toast

### ISSUE THREAD

**Issue by vertonghenb** [AlexKvazos/VanillaToasts#12]
Is it possible to set the location of the toast?
for example:
Bottom-Right instead of top right?

**Comment by alexkvazos** [comment]
Good observation, not yet.
I can take care of this later on or if you'd like, you can PR 😄

**Comment by markwalt** [comment]
Adding a no repeat option would be useful so that it prevents the same toast from stacking. If I knew how to i'd share the update I made, it's only a few lines of code.

**Comment by davidrock** [comment]
There is a PR for that, it is waiting to be merged since July/19 . Is the creator yet around ?

**Comment by alexkvazos** [comment]
Fixed by #15 

Thanks @sdkcodes
