### ISSUE TITLE
Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by d-oliveros** [AlexKvazos/VanillaToasts#2]
After doing `VanillaToasts.create()`, the app breaks with the following error message:

```
TypeError: Cannot read property 'appendChild' of null
    at Object.VanillaToasts.create
    at ...
```

**Comment by d-oliveros** [comment]
To solve this issue, I had to do `setTimeout(() => VanillaToasts.create(), 500);`

**Comment by ColtraneNadler** [comment]
Issue has been handled, and a pull request has been submitted. Now- your solution will still work, but moving forwards, you will be informed to invoke the create method once the dom has finished loading, as opposed to receiving an unwanted TypeError.

**Comment by d-oliveros** [comment]
Thanks @ColtraneNadler !
