### ISSUE TITLE
Timeout not doing anything

### ISSUE THREAD

**Issue by d-oliveros** [AlexKvazos/VanillaToasts#4]
When creating a toast like this, the toast is not disappearing after the timeout.

```
VanillaToasts.create({
      title: 'Some title',
      text: 'Some text',
      timeout: 1000
});
```

**Comment by ColtraneNadler** [comment]
I am unable to replicate this issue, timeouts work fine.

**Comment by d-oliveros** [comment]
Yeah, I can't reproduce it neither. I'll close this for now.
