### ISSUE TITLE
Remove this bracket since it breaks the code

### ISSUE THREAD

**Issue by paramientos** [AlexKvazos/VanillaToasts#41]
https://github.com/AlexKvazos/VanillaToasts/blob/56253391c00fc39768f2148973be5204eaeb2dcb/vanillatoasts.js#L85

**Comment by scaliebe** [comment]
I have created a pull request ( #43 ) for this issue

**Comment by alexkvazos** [comment]
Fixed by #43, thanks @scaliebe!
